//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReceiver.SpeedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpeedServiceReference.ISpeedService")]
    public interface ISpeedService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpeedService/DoWork", ReplyAction="http://tempuri.org/ISpeedService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpeedService/DoWork", ReplyAction="http://tempuri.org/ISpeedService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpeedService/HandleNewSale", ReplyAction="http://tempuri.org/ISpeedService/HandleNewSaleResponse")]
        void HandleNewSale(Core.SalesOrderHeader sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpeedService/HandleNewSale", ReplyAction="http://tempuri.org/ISpeedService/HandleNewSaleResponse")]
        System.Threading.Tasks.Task HandleNewSaleAsync(Core.SalesOrderHeader sale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpeedService/ExpireSalesRealtimeView", ReplyAction="http://tempuri.org/ISpeedService/ExpireSalesRealtimeViewResponse")]
        void ExpireSalesRealtimeView();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpeedService/ExpireSalesRealtimeView", ReplyAction="http://tempuri.org/ISpeedService/ExpireSalesRealtimeViewResponse")]
        System.Threading.Tasks.Task ExpireSalesRealtimeViewAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpeedServiceChannel : DataReceiver.SpeedServiceReference.ISpeedService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpeedServiceClient : System.ServiceModel.ClientBase<DataReceiver.SpeedServiceReference.ISpeedService>, DataReceiver.SpeedServiceReference.ISpeedService {
        
        public SpeedServiceClient() {
        }
        
        public SpeedServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpeedServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpeedServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpeedServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public void HandleNewSale(Core.SalesOrderHeader sale) {
            base.Channel.HandleNewSale(sale);
        }
        
        public System.Threading.Tasks.Task HandleNewSaleAsync(Core.SalesOrderHeader sale) {
            return base.Channel.HandleNewSaleAsync(sale);
        }
        
        public void ExpireSalesRealtimeView() {
            base.Channel.ExpireSalesRealtimeView();
        }
        
        public System.Threading.Tasks.Task ExpireSalesRealtimeViewAsync() {
            return base.Channel.ExpireSalesRealtimeViewAsync();
        }
    }
}
